import os
#
#
# apk_path = 'F:/research/data/apk_simple_name/1Rramp-Android.apk'
# os.system(r'D:\IT\JavaJDK\bin\java.exe "-javaagent:D:\IT\IntelliJ IDEA 2020.3.3\lib\idea_rt.jar=54890:D:\IT\IntelliJ IDEA 2020.3.3\bin" -Dfile.encoding=UTF-8 -classpath F:\research\data\ApkScan\ApkScan\bin;D:\IT\JavaJDK\jre\lib\charsets.jar;D:\IT\JavaJDK\jre\lib\deploy.jar;D:\IT\JavaJDK\jre\lib\ext\access-bridge-64.jar;D:\IT\JavaJDK\jre\lib\ext\cldrdata.jar;D:\IT\JavaJDK\jre\lib\ext\dnsns.jar;D:\IT\JavaJDK\jre\lib\ext\jaccess.jar;D:\IT\JavaJDK\jre\lib\ext\jfxrt.jar;D:\IT\JavaJDK\jre\lib\ext\localedata.jar;D:\IT\JavaJDK\jre\lib\ext\nashorn.jar;D:\IT\JavaJDK\jre\lib\ext\sunec.jar;D:\IT\JavaJDK\jre\lib\ext\sunjce_provider.jar;D:\IT\JavaJDK\jre\lib\ext\sunmscapi.jar;D:\IT\JavaJDK\jre\lib\ext\sunpkcs11.jar;D:\IT\JavaJDK\jre\lib\ext\zipfs.jar;D:\IT\JavaJDK\jre\lib\javaws.jar;D:\IT\JavaJDK\jre\lib\jce.jar;D:\IT\JavaJDK\jre\lib\jfr.jar;D:\IT\JavaJDK\jre\lib\jfxswt.jar;D:\IT\JavaJDK\jre\lib\jsse.jar;D:\IT\JavaJDK\jre\lib\management-agent.jar;D:\IT\JavaJDK\jre\lib\plugin.jar;D:\IT\JavaJDK\jre\lib\resources.jar;D:\IT\JavaJDK\jre\lib\rt.jar;F:\research\data\ApkScan\ApkScan\libs\axml-2.0.jar;F:\research\data\ApkScan\ApkScan\libs\AXMLPrinter2.jar;F:\research\data\ApkScan\ApkScan\libs\soot-4.1.0-jar-with-dependencies.jar edu.monash.apkscan.ApkScanMain ' + apk_path)
# r'D:\IT\JavaJDK\bin\java.exe "-javaagent:D:\IT\IntelliJ IDEA 2020.3.3\lib\idea_rt.jar=54890:D:\IT\IntelliJ IDEA 2020.3.3\bin" -Dfile.encoding=UTF-8 -classpath F:\research\data\ApkScan\ApkScan\bin;D:\IT\JavaJDK\jre\lib\charsets.jar;D:\IT\JavaJDK\jre\lib\deploy.jar;D:\IT\JavaJDK\jre\lib\ext\access-bridge-64.jar;D:\IT\JavaJDK\jre\lib\ext\cldrdata.jar;D:\IT\JavaJDK\jre\lib\ext\dnsns.jar;D:\IT\JavaJDK\jre\lib\ext\jaccess.jar;D:\IT\JavaJDK\jre\lib\ext\jfxrt.jar;D:\IT\JavaJDK\jre\lib\ext\localedata.jar;D:\IT\JavaJDK\jre\lib\ext\nashorn.jar;D:\IT\JavaJDK\jre\lib\ext\sunec.jar;D:\IT\JavaJDK\jre\lib\ext\sunjce_provider.jar;D:\IT\JavaJDK\jre\lib\ext\sunmscapi.jar;D:\IT\JavaJDK\jre\lib\ext\sunpkcs11.jar;D:\IT\JavaJDK\jre\lib\ext\zipfs.jar;D:\IT\JavaJDK\jre\lib\javaws.jar;D:\IT\JavaJDK\jre\lib\jce.jar;D:\IT\JavaJDK\jre\lib\jfr.jar;D:\IT\JavaJDK\jre\lib\jfxswt.jar;D:\IT\JavaJDK\jre\lib\jsse.jar;D:\IT\JavaJDK\jre\lib\management-agent.jar;D:\IT\JavaJDK\jre\lib\plugin.jar;D:\IT\JavaJDK\jre\lib\resources.jar;D:\IT\JavaJDK\jre\lib\rt.jar;F:\research\data\ApkScan\ApkScan\libs\axml-2.0.jar;F:\research\data\ApkScan\ApkScan\libs\AXMLPrinter2.jar;F:\research\data\ApkScan\ApkScan\libs\soot-4.1.0-jar-with-dependencies.jar edu.monash.apkscan.ApkScanMain'

# apk_root = r'F:\research\data\apk_simple_name'
# #apk_root = os.path.join('F:', 'research', 'data', 'apk_simple_name')
# print(apk_root)

permissions = ['android.speech.tts.TextToSpeech.getLanguage()java.util.Locale  ::  android.permission.BROADCAST_STICKY',
                    'android.accounts.AccountAuthenticatorActivity.removeStickyBroadcast']
print(permissions[0].split('::')[-1].strip())